// src/lib/mockStores.ts
import { Store } from "./types";

export const stores: Store[] = [
  {
    slug: "moda-bella",
    name: "Moda Bella",
    location: "São Paulo – SP",
    whatsapp: "5511999999999",
    open: "Sempre aberto",
    coverEmojis: "👗👜👟",
    logoEmoji: "🛍️",
    categories: ["Todas", "Roupas", "Calçados", "Acessórios", "Promoções", "Novidades"],
    products: [
      {
        id: "1",
        name: "Tênis Runner Pro",
        description: "Solado ultra-confortável com amortecimento tecnológico para o dia a dia.",
        price: 289,
        oldPrice: 350,
        emoji: "👟",
        bg: "linear-gradient(135deg,#f3e7ff,#ffe7f0)",
        category: "Calçados",
        tag: "Recomendado",
        status: "instock",
        featured: true,
      },
      {
        id: "2",
        name: "Bolsa Couro Legítimo",
        description: "Acabamento premium, alças ajustáveis e compartimento interno espaçoso.",
        price: 459,
        emoji: "👜",
        bg: "linear-gradient(135deg,#ffe7f0,#fff0e0)",
        category: "Acessórios",
        tag: "Novidade",
        status: "low",
        featured: true,
      },
      {
        id: "3",
        name: "Relógio Smart X2",
        description: "Monitor cardíaco, GPS e bateria de 7 dias. Estilo e tecnologia juntos.",
        price: 199,
        oldPrice: 249,
        emoji: "⌚",
        bg: "linear-gradient(135deg,#fff0e0,#fffbe0)",
        category: "Acessórios",
        tag: "Novidade",
        status: "instock",
        featured: false,
      },
      {
        id: "4",
        name: "Vestido Floral",
        description: "Tecido leve e fresco, estampa exclusiva para o verão 2025.",
        price: 149,
        oldPrice: 210,
        emoji: "👗",
        bg: "linear-gradient(135deg,#eaf3de,#e1f5ee)",
        category: "Roupas",
        status: "out",
        featured: true,
      },
      {
        id: "5",
        name: "Óculos de Sol",
        description: "Proteção UV400, armação reforçada e estilo que combina com tudo.",
        price: 89,
        emoji: "🕶️",
        bg: "linear-gradient(135deg,#e6f1fb,#eeedfe)",
        category: "Acessórios",
        status: "instock",
        featured: false,
      },
      {
        id: "6",
        name: "Jaqueta Jeans",
        description: "Corte moderno, lavagem diferenciada. Perfeita para qualquer estação.",
        price: 319,
        oldPrice: 389,
        emoji: "🧥",
        bg: "linear-gradient(135deg,#e6f1fb,#dce8f7)",
        category: "Roupas",
        tag: "Promoção",
        status: "instock",
        featured: false,
      },
      {
        id: "7",
        name: "Sandália Rasteira",
        description: "Conforto e elegância para os dias quentes. Disponível em 3 cores.",
        price: 79,
        emoji: "👡",
        bg: "linear-gradient(135deg,#fbeaf0,#fff0e0)",
        category: "Calçados",
        status: "instock",
        featured: false,
      },
      {
        id: "8",
        name: "Cinto de Couro",
        description: "Couro genuíno, fivela dourada. Acabamento de alta qualidade.",
        price: 69,
        emoji: "👔",
        bg: "linear-gradient(135deg,#f1efe8,#e8e4d8)",
        category: "Acessórios",
        status: "instock",
        featured: false,
      },
    ],
  },
];

export function getStore(slug: string): Store | undefined {
  return stores.find((s) => s.slug === slug);
}
